const socket=io(); let room=null, priv=null, lastResult=null;
const $=id=>document.getElementById(id); const speak=t=>{ if('speechSynthesis' in window){ speechSynthesis.cancel(); speechSynthesis.speak(new SpeechSynthesisUtterance(t)); }};
function createRoom(){socket.emit('createRoom',{name:$('name').value},r=>{if(!r.ok)alert(r.error);});}
function joinRoom(){socket.emit('joinRoom',{code:$('code').value,name:$('name').value},r=>{if(!r.ok)alert(r.error);});}
socket.on('room',r=>{room=r; $('home').classList.add('hidden'); $('game').classList.remove('hidden'); render();});
socket.on('private',p=>{priv=p; render();}); socket.on('result',r=>{lastResult=r; render();});
function me(){return room?.players.find(p=>p.id===priv?.you?.id)} function host(){return me()?.isHost}
function render(){ if(!room||!priv)return; $('roomTitle').innerHTML=`Room Code: <b>${room.code}</b> <span class="small">(${room.phase})</span>`; $('players').innerHTML='<h3>Players</h3>'+room.players.map(p=>`<div class="player">${p.name} ${p.isHost?'👑':''} ${p.connected?'':'(offline)'}</div>`).join('');
$('private').innerHTML=priv.you.role?`<div class="role"><div class="emoji pulse">${priv.you.role.emoji}</div><h2>${priv.you.role.name}</h2><p>${priv.you.role.desc}</p><p class="small">Initial role: ${priv.you.initialRole?.name||''}. Final card may change during night.</p></div>`:'';
$('log').innerHTML='<h3>Game Log</h3>'+room.log.map(x=>`<div class="log">${x}</div>`).join(''); actions(); }
function actions(){let h=''; if(room.phase==='lobby'&&host()) h+=`<button onclick="socket.emit('startGame')">Deal Roles</button>`; if(room.phase==='reveal'&&host()) h+=`<button onclick="socket.emit('beginNight')">Begin Night</button>`;
if(room.phase==='night'){ const role=room.activeRole; h+=`<h3>Night Action: ${role}</h3><button onclick="speak('Wake up ${role}. Perform your action quietly.')">🔊 Voice Narration</button>`; if(host())h+=`<button onclick="socket.emit('nextNight')">Next Night Role</button>`; h+=nightAction(role); }
if(room.phase==='discussion'){h+=`<button onclick="speak('Everyone wake up. You have five minutes to discuss and find the wolf.')">🔊 Start Voice Discussion</button>`; if(host())h+=`<button onclick="socket.emit('goVote')">Go to Vote</button>`;}
if(room.phase==='vote'){ h+=voteUI(); if(host())h+=`<button onclick="socket.emit('showResult')">Show Result</button>`;}
if(room.phase==='result'&&lastResult){ h+=`<h2 class="${lastResult.villageWins?'ok':'bad'}">${lastResult.villageWins?'Village Wins 🎉':'Wolf Team Wins 🐺'}</h2><p>Eliminated: ${lastResult.eliminated.join(', ')||'Nobody'}</p><h3>Final Roles</h3>`+lastResult.roles.map(x=>`<div class="step">${x.name}: ${x.role.emoji} ${x.role.name}</div>`).join('')+`<h3>Center</h3>`+lastResult.center.map(x=>`<div class="step">${x.emoji} ${x.name}</div>`).join('');}
$('actions').innerHTML=h;}
function playerOptions(excludeSelf=false){return room.players.filter(p=>!excludeSelf||p.id!==priv.you.id).map(p=>`<option value="${p.id}">${p.name}</option>`).join('')}
function nightAction(role){ const initial=priv.you.initialRole?.id; if(role!==initial) return '<p class="small">Wait quietly. This is not your role phase.</p>'; if(role==='seer') return `<div class="step"><button onclick="seerCenter()">Check 2 Center Cards</button><select id="seerTarget">${playerOptions()}</select><button onclick="seerPlayer()">Check Player</button><div id="seen"></div></div>`; if(role==='robber') return `<div class="step"><p>Swipe/swap with one player:</p><select id="robberTarget">${playerOptions(true)}</select><button onclick="robberSwap()">Swap & Reveal New Card</button><div id="seen"></div></div>`; if(role==='troublemaker') return `<div class="step"><p>Swap two other players:</p><select id="t1">${playerOptions(true)}</select><select id="t2">${playerOptions(true)}</select><button onclick="troubleSwap()">Swap Cards</button><div id="seen"></div></div>`; if(role==='insomniac') return `<div class="step"><button onclick="insomniacCheck()">Check My Final Card</button><div id="seen"></div></div>`; if(role==='wolf') return `<div class="step">Open your eyes and identify other wolves. If you are alone, bluff carefully.</div>`; return '<p>No action.</p>'; }
function seerCenter(){socket.emit('seerCheck',{type:'center'},r=>showSeen(r));} function seerPlayer(){socket.emit('seerCheck',{type:'player',targetId:$('seerTarget').value},r=>showSeen(r));}
function robberSwap(){socket.emit('robberSwap',{targetId:$('robberTarget').value},r=>{$('seen').innerHTML=r.ok?`New role: ${r.newRole.emoji} ${r.newRole.name}`:r.error;});}
function troubleSwap(){socket.emit('troublemakerSwap',{a:$('t1').value,b:$('t2').value},r=>{$('seen').innerHTML=r.ok?'Cards swapped successfully.':r.error;});}
function insomniacCheck(){socket.emit('insomniacCheck',r=>{$('seen').innerHTML=r.ok?`Your final role: ${r.role.emoji} ${r.role.name}`:r.error;});}
function showSeen(r){$('seen').innerHTML=r.ok?r.seen.map(x=>`${x.name}: ${x.role.emoji} ${x.role.name}`).join('<br>'):r.error;}
function voteUI(){return `<h3>Vote</h3><select id="voteTarget">${playerOptions()}</select><button onclick="socket.emit('vote',{targetId:$('voteTarget').value})">Submit Vote</button>`;}
